pipeline:
  
  test:
    image: waddle/vapor-builder
    commands:
      - swift test
  
  publish:
    image: plugins/docker
    repo: waddle/web-api
    auto_tag: true
    secrets: [ docker_username, docker_password ]
    when:
      status:  [ success ]

branches: master