pipeline:
  build:
    image: waddle/vapor-builder
    commands:
      - mkdir -p /build/lib && cp -R /usr/lib/swift/linux/*.so /build/lib
      - swift build -c release && mv `swift build -c release --show-bin-path` /build/bin
  
  test:
    image: waddle/vapor-runner
    commands:
      - swift test
  
  publish:
    image: plugins/docker
    repo: waddle/web-api
    tags: latest
    secrets: [ docker_username, docker_password ]
    when:
      status:  [ success ]

branches: master