workspace:
  base: /app

pipeline:

  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.build
    volumes:
      - /tmp/cache:/cache

  build:
    image: waddle/vapor-builder
    commands:
      - swift build

    when:
      event: push

  test:
    image: waddle/vapor-builder
    commands:
      - swift test

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./.build
    volumes:
      - /tmp/cache:/cache

  publish:
    image: plugins/docker
    repo: waddle/web-api
    auto_tag: true
    secrets: [ docker_username, docker_password ]
    when:
      status: [ success ]
      branch: master

services:
  database:
    image: postgres:10.3
    environment:
      - POSTGRES_PASSWORD=vapor
      - POSTGRES_USER=vapor
      - POSTGRES_DB=vapor
