workspace:
  base: /app

pipeline:

  build:
    image: waddle/vapor-builder
    commands:
      - swift build
    when:
      event: push

  test:
    image: waddle/vapor-builder
    commands:
      - swift test --skip-build

  publish:
    image: plugins/docker
    repo: waddle/web-api
    auto_tag: true
    secrets: [ docker_username, docker_password ]
    when:
      status: [ success ]
      branch: master
