workspace:
  base: /app

pipeline:

  build:
    image: waddle/vapor-builder
    commands:
      - vapor build

    when:
      event: push

  test:
    image: waddle/vapor-builder
    commands:
      - vapor test

  publish:
    image: plugins/docker
    repo: waddle/web-api
    auto_tag: true
    secrets: [ docker_username, docker_password ]
    when:
      status: [ success ]
      branch: master

services:
  database:
    image: postgres:10.3
    environment:
      - POSTGRES_PASSWORD=vapor
      - POSTGRES_USER=vapor
      - POSTGRES_DB=vapor